// clientes.js
const clientes = {
    florencia: {
        evento: "MIS XV",
        nombre: "Florencia",
        mensaje: "¡Te espero este sábado 19!",
        css: "style1.css",
        audio: "florencia.mp3",
        eventDate: new Date("2025-11-01T14:00:00"),
        fechaTexto: "1 de Noviembre de 2025 - 14:00 hs",
        ics: "florencia.ics",
        miniMapa: "https://www.google.com/maps/embed?...",
        linkmaps: "https://maps.app.goo.gl/ma4DX7fvmG2RXff8A",
        numWhatsapp: "https://wa.me/5491234567890?text=¡Hola! Confirmo mi asistencia al cumple de Florencia 🎉",
        textoLibre: "¡Celebremos juntos mis dulces 15!...",
        linkCBU: "https://link.mercadopago.com.ar/pilus27",
        cbutext: "Queridos amigos y familiares:CBU",
        linkSpotify: "https://open.spotify.com/playlist/...",
        linkForm: "https://forms.gle/LQ3wK1f2yCWpxeAf9",
        dresstext: "Vení lindx pa las pics"
    },
    lucia: {
        evento: "Mi Boda",
        nombre: "Lucia",
        mensaje: "¡Será un día inolvidable, no faltes!",
        css: "style2.css",
        audio: "lucia.mp3",
        eventDate: new Date("2027-05-27T14:00:00"),
        fechaTexto: "27 de Mayo de 2027 - 14:00 hs",
        ics: "lucia.ics",
        miniMapa: "https://www.google.com/maps/embed?...",
        linkmaps: "https://maps.app.goo.gl/ma4DX7fvmG2RXff8A",
        numWhatsapp: "https://wa.me/5491234569078?text=¡Hola! Confirmo mi asistencia a la boda de Lucia 🎉",
        textoLibre: "Con gran emoción y felicidad, [Nombres de los novios]...",
        linkCBU: "https://link.mercadopago.com.ar/pilus24",
        cbutext: "Queridos amigos y familiares:CBU",
        linkSpotify: "https://open.spotify.com/playlist/...",
        linkForm: "https://forms.gle/LQ3wK1f2yCWpxeAf8",
        dresstext: "Vení lindx pa las pics"
    },
    marcos: {
        evento: "25",
        nombre: "Marcos",
        mensaje: "¡Estás invitado a mis 15 + 10!",
        css: "style3.css",
        audio: "marcos.mp3",
        eventDate: new Date("2025-09-14T12:00:00"),
        fechaTexto: "14 de Septiembre de 2025 - 12:00 hs",
        miniMapa: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d818.9792784841574!2d-58.629674900000005!3d-34.80802709999999!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x95bcc4b34cbc5a65%3A0x81de57f90d96a36b!2sEsteco%201800-1686%2C%20B1763AOH%20Virrey%20del%20Pino%2C%20Provincia%20de%20Buenos%20Aires!5e0!3m2!1ses-419!2sar!4v1756564211034!5m2!1ses-419!2sar",
        linkmaps: "https://maps.app.goo.gl/pmb9wPJb2ZLv8sy77",
        numWhatsapp: "https://wa.me/541136583081?text=¡Nos vemos el 14 Marquinhos!",
        textoLibre: "¡Voy a celebrar mis 25 años! Un cuarto de siglo merece un festejo especial y, no hay mejor manera de hacerlo que con vos presente. Quedas formalmente invitado a a compartir un dia lleno de risas y música. Tu presencia hara que este dia sea aun más especial, ¡Te espero!",
        linkCBU: "https://link.mercadopago.com.ar/pilus27",
        cbutext: "Queridos amigos y familiares: Quiero agradecerles de corazón por acompañarme en este dia tan especial. Su presencia es, sin duda alguna, el mejor regalo que puedo recibir. Sé que no es fácil elegir algún absequio o encontrar el tiempo para hacerlo. Por eso, si lo desean, pueden optar por realizarlo a travez de una transferencia. Lo importante es que podamos compartir juntos este momento y celebrar. Les agradezco desde ya por el cariño, y la buena energía que siempre me brindan. ¡Nos vemos en la fiesta!",
        linkSpotify: "https://open.spotify.com/playlist/3DCDbwJkYtehEeemQKdaQ4?si=yVI6WbgzTpKHQm0xPNexOw&pi=6jDy7ed7SQiBb",
        linkForm: "https://forms.gle/LQ3wK1f2yCWpxeAf9",
        dresstext: "Vení lindx para las pics",
        nombre:"Marcos",
        fotos:[
            "./img/clienteMarcos/foto1.jpg",
            "./img/clienteMarcos/foto3.jpg",
            "./img/clienteMarcos/foto4.jpg",
            "./img/clienteMarcos/foto5.jpg",
            "./img/clienteMarcos/foto6.jpg",
            "./img/clienteMarcos/foto7.jpg",
        ]
    },
    eagles: {
        evento: "Fiesta de fin de año",
        nombre: "Eagles",
        mensaje: "¡Fiesta asegurada, no podés faltar!",
        css: "style4.css",
        audio: "eagles.mp3",
        eventDate: new Date("2025-12-01T14:00:00"),
        fechaTexto: "1 de Diciembre de 2025 - 14:00 hs",
        ics: "eagles.ics",
        miniMapa: "https://www.google.com/maps/embed?...",
        linkmaps: "https://maps.app.goo.gl/ma4DX7fvmG2RXff8A",
        numWhatsapp: "https://wa.me/5491234657890?text=¡Hola! Confirmo mi asistencia a la fiesta de Eagles 🎉",
        textoLibre: "Nos complace invitarlo cordialmente...",
        linkCBU: "https://link.mercadopago.com.ar/pilus26",
        cbutext: "Queridos amigos y familiares:CBU",
        linkSpotify: "https://open.spotify.com/playlist/...",
        linkForm: "https://forms.gle/LQ3wK1f2yCWpxeAf6",
        dresstext: "Vení lindx pa las pics"
    }
};

// Hacemos accesible globalmente
window.clientes = clientes;
